name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 📥 Checkout code
      - name: Checkout
        uses: actions/checkout@v7

      # 📦 Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      # 🟢 Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: "pnpm"

      # 📥 Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 🏗 Build (turbo sẽ tự tối ưu nếu có)
      - name: Build
        run: pnpm build
